### ISSUE TITLE
Auth Plain

### ISSUE THREAD

**Issue by denisovdenis** [kaize/mail_sandbox_web#6]
Пытаемся настроить MediaWiki, чтобы она стучала в песочницу, но не выходит, так как стандартный модуль Pear/Mail основывается на спецификации RFC 2554, которая предполагает, что после отправки команды AUTH PLAIN, сервер ответит кодом 334 и в ответ получит Base64.

**Comment by zzet** [comment]
@denisovdenis Issue больше относится к https://github.com/kaize/mail_sandbox

**Comment by denisovdenis** [comment]
@zzet спасибо!
